name: Fetch Daily Submissions

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  fetch-submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install

      - name: Generate Markdown File
        id: generate_markdown
        run: |
          npx tsx generateMarkdown.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          commit-message: (Automated) New Page
          title: (Automated) New Page Added
          body: This is an automated pull request to update the daily submissions.
          base: main
          branch: daily-submissions
          delete-branch: true
